name: Daily Model Training

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Requirements
        run: pip install pandas pymongo scikit-learn

      - name: Run Model Training Script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python 02_training_pipeline.py
